routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;


Auth::routes();
Route::get('/redirect/{provider}', 'SocialAuthController@redirect');
Route::get('/callback/{provider}', 'SocialAuthController@callback');
Route::get('/logout', 'Auth\LoginController@logout');

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'website\HomeController@home');
});


Route::group(['prefix' => 'webadmin', 'middleware' => ['webadmin']], function () {
    Route::get('/dashboard', 'admin\DashboardController@index');
    Route::get('/logout', 'Auth\LoginController@logout');
    Route::resource('/users', 'admin\UsersController');
    Route::resource('/admins', 'admin\AdminsController');
    Route::resource('/settings', 'admin\SettingController');
    Route::resource('/categories', 'admin\CategoriesController');
    Route::resource('/subcategories', 'admin\SubCategoriesController');
    Route::resource('/categories-options', 'admin\CategoriesOptionsController');
    Route::resource('/countries', 'admin\CountryController');
    Route::resource('/cities', 'admin\CitiesController');
    Route::resource('/products', 'admin\ProductsController');
    Route::get('/get-product-category-data/{product_id}/{category_id}', 'admin\ProductsController@ProductData');
    Route::resource('/sliders', 'admin\SlidersController');


});
Route::post('/search', 'website\ProductsController@search');
Route::get('/categories/{id}', 'website\ProductsController@getSubCategories');
Route::get('/product/{id}', 'website\ProductsController@getProduct');
Route::get('/products/{cat_id}', 'website\ProductsController@getProducts');
Route::post('/search-filter', 'website\ProductsController@searchFilter');


Route::group(['middleware' => ['auth']], function () {
    Route::get('add-ad', 'website\ProductsController@AddProduct');
    Route::post('/add-ad', 'website\ProductsController@SaveProduct');
    Route::post('/add-ad/image-ajax-upload', 'website\ProductsController@uploadAdImage');
    Route::get('/profile', 'website\UsersController@profile');
    Route::get('/favourites', 'website\UsersController@favourites');
    Route::get('/chats', 'website\UsersController@chats');
});
Route::get('/information/create/ajax-countries', function () {
    $country_id = $_GET['country_id'];
    $cities = \App\Models\City::where('country_id', '=', $country_id)->get();
    return json_encode($cities);

});
Route::get('/information/create/ajax-categories', function () {
    $category_id = $_GET['category_id'];
    $subcategories = \App\Models\Category::where('parent_id', '=', $category_id)->get();
    return json_encode($subcategories);

});
Route::get('/information/create/ajax-types', function () {
    $subcategory_id = $_GET['subcategory_id'];
    $types = \App\Models\Category::where('parent_id', '=', $subcategory_id)->get();
    return json_encode($types);

});
Route::get('/getchat', function () {
    $sender_id = $_GET['sender_id'];
    $receiver_id = $_GET['receiver_id'];
    $messages = \App\Models\Message::where([['sender_id', $sender_id], ['receiver_id', $receiver_id]])
        ->orWhere(function ($query) use ( $sender_id,$receiver_id) {
            return $query->where([['sender_id', $receiver_id], ['receiver_id', $sender_id]]);
        })->with('sender')->with('receiver')->get();
    return json_encode($messages);

});
Route::get('/sendmessage', function () {
    $sender_id = $_GET['sender_id'];
    $receiver_id = $_GET['receiver_id'];
    $message = $_GET['message'];
    $msg=\App\Models\Message::create([
        'sender_id'=>$sender_id,
        'receiver_id'=>$receiver_id,
        'message'=>$message,

    ]);
     return json_encode($msg);

});
Route::get('/change-country', function () {
    $country_id = $_GET['country_id'];
    session(['country_id' => $country_id]);

});
Route::get('/change-city', function () {
    $city_id = $_GET['city_id'];
    session(['city_id' => $city_id]);

});

app/Models/Slider.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Slider extends Model
{
    protected $table = 'sliders';
    protected $guarded = [];

    public $timestamps = true;
}

app/Http/Controllers/admin/SlidersController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use App\Models\Slider;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class SlidersController extends Controller
{
    public function index()
    {
        $sliders = Slider::orderBy('created_at', 'ASC')->get();
        return view('admin.sliders.index', compact('sliders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.sliders.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'photo' => 'required|image|mimes:jpeg,png,jpg,gif,svg',
            'location' => 'required'
        ]);

        $imageName = Str::random(10) . '.' . $request->file('photo')->extension();
        $request->file('photo')->move(
            base_path() . '/public/uploads/sliders/', $imageName
        );
        Slider::create([
            'photo' => '/uploads/sliders/' . $imageName,
            'location' => $request->location
        ]);


        return redirect('/webadmin/sliders')->withFlashMessage(json_encode(['success' => true, 'msg' => 'تم اضافة البنر بنجاح']));

    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $slider = Slider::find($id);
        return view('admin.sliders.edit', compact('slider'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $slider = Slider::find($id);
        $request->validate([
            'location' => 'required'
//            'photo' => 'required|image|mimes:jpeg,png,jpg,gif,svg'
        ]);

        $slider->update([
            'location' => $request->location
        ]);
        if ($request->photo) {
            $imageName = Str::random(10) . '.' . $request->file('photo')->extension();
            $request->file('photo')->move(
                base_path() . '/public/uploads/sliders/', $imageName
            );
            $slider->photo = '/uploads/sliders/' . $imageName;
            $slider->save();
        }
        return redirect('/webadmin/sliders')->withFlashMessage(json_encode(['success' => true, 'msg' => 'تم تعديل البنر بنجاح']));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Slider::destroy($id);
        return redirect('/webadmin/sliders')->withFlashMessage(json_encode(['success' => true, 'msg' => 'تم حذف البنر بنجاح']));

    }
}

resources/views/admin/sliders/add.blade.php
@extends('admin.layouts.app')

@section('title')
   اضافة بنر اعلاني
@endsection
@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">الرئيسية</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/sliders')}}" class="m-menu__link">
            <span class="m-menu__link-text"> البنرات الاعلانية</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item" style="background: #e0deff;">
        <a href="" class="m-menu__link">
            <span class="m-menu__link-text">اضافة بنر اعلاني</span>
            <i class="m-menu__hor-arrow la la-angle-down"></i>
        </a>
    </li>
@endsection

@section('header')
@endsection

@section('content')

    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
					</span>
                    <h3 class="m-portlet__head-text">
                       اضافة اسلايدر
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        <form class="m-form m-form--fit m-form--label-align-right" action="/webadmin/sliders" method="post" enctype="multipart/form-data">
            {{ csrf_field() }}

            <div class="m-portlet__body">
                @include('admin.sliders.form')
            </div>
            <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                <div class="m-form__actions m-form__actions--solid">
                    <div class="row">
                        <div class="col-lg-2"></div>
                        <div class="col-lg-6">
                            <button type="submit" class="btn btn-success">اضافة </button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <!--end::Form-->
    </div>
    <!--end::Portlet-->
@endsection
@section('footer')
    <script type="text/javascript">

    </script>
@endsection

resources/views/admin/sliders/edit.blade.php
@extends('admin.layouts.app')

@section('title')
    تعديل بنر اعلاني
@endsection
@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">الرئيسية</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/sliders')}}" class="m-menu__link">
            <span class="m-menu__link-text">البنرات الاعلانية </span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item" style="background: #e0deff;">
        <a href="javascript:;" class="m-menu__link">
            <span class="m-menu__link-text">تعديل بنر اعلاني </span>
            <i class="m-menu__hor-arrow la la-angle-down"></i>
        </a>
    </li>
@endsection

@section('header')
@endsection

@section('content')

    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
					</span>
                    <h3 class="m-portlet__head-text">
                        تعديل اسلايدر
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        {!! Form::model($slider,['route' => ['sliders.update' , $slider->id],'method'=> 'PATCH','class'=>'m-form m-form--fit m-form--label-align-right',"enctype"=>"multipart/form-data"]) !!}
        <div class="m-portlet__body">
            @include('admin.sliders.form')
        </div>
        <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
            <div class="m-form__actions m-form__actions--solid">
                <div class="row">
                    <div class="col-lg-2"></div>
                    <div class="col-lg-6">
                        <button type="submit" class="btn btn-success">تعديل</button>
                    </div>
                </div>
            </div>
        </div>
    {!! Form::close() !!}
    <!--end::Form-->
    </div>
    <!--end::Portlet-->
@endsection
@section('footer')
    <script type="text/javascript">

    </script>
@endsection

resources/views/admin/sliders/form.blade.php
<div class="form-group m-form__group row">
    <label for="city_id" class="col-lg-2 col-form-label">الموقع: </label>
    <div class="col-lg-10{{ $errors->has('location') ? ' has-danger' : '' }}">
        <select name="city_id" data-url="{{url('api/get-categories/')}}" id="city_id" class="form-control city_id m-input" required>
            <option value="">قم باختيار مكان البنر </option>
            <option value="1" @if (old('location') == 1) selected="selected" @endif>الصفحة الرئيسية</option>
            <option value="2" @if (old('location') == 2) selected="selected" @endif>صفحة البحث</option>
            <option value="3" @if (old('location') == 3) selected="selected" @endif>صغحة تفاصيل الاعلان</option>
        </select>
        @if ($errors->has('location'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('location') }}</strong>
            </span>
        @endif
    </div>
</div>

<div class="form-group m-form__group row">
    <label class="col-lg-2 col-form-label">الصورة: </label>
    <div class="col-lg-10{{ $errors->has('photo') ? ' has-danger' : '' }}">
        <input type="file" name="photo"   class="form-control uploadinput">
        @if ($errors->has('photo'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('photo') }}</strong>
            </span>
        @endif
    </div>

</div>
@if(isset($slider) && $slider->photo)
    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-6" style="margin-bottom: 10px;">
            <img
                    data-src="holder.js/800x400?auto=yes&amp;bg=777&amp;fg=555&amp;text=First slide"
                    alt="First slide [800x4a00]"
                    src="{{$slider->photo}}"
                    style="height: 150px; width: 150px"
                    data-holder-rendered="true">
        </div>

    </div>
@endif

resources/views/admin/sliders/index.blade.php
@extends('admin.layouts.app')
@section('title')
    البنرات الاعلانية
@endsection

@section('header')
    {!! Html::style('admin/vendors/custom/datatables/datatables.bundle.rtl.css') !!}
@endsection

@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">الرئيسية</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item active-top-bar">
        <a href="javascript:;" class="m-menu__link">
            <span class="m-menu__link-text">البنرات الاعلانية</span>
            <i class="m-menu__hor-arrow la la-angle-down"></i>
        </a>
    </li>

@endsection

@section('content')
    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        البنرات الاعلانية
                    </h3>
                </div>
            </div>
        </div>
        <div class="m-portlet__body">
            <div><a href="{{route('sliders.create')}}" style="margin-bottom:20px"
                    class="btn btn_primary btn btn-danger"><i class=" fa fa-edit"></i> اضف بنر اعلاني</a></div>


            <!--begin: Datatable -->
            <table class="table table-striped- table-bordered table-hover table-checkable" id="m_table_country">
                <thead>
                <tr>
                    <th>#</th>
                    <th>الصوره</th>
                    <th>الموقع</th>
                    <th>الاجراءات</th>
                </tr>
                </thead>
                <tbody>
                @foreach($sliders as $index=>$slider)
                    <tr>
                        <td>{{$index +1}}</td>
                        <td><img  width="120px;" height="120px;" src="{{$slider->photo}}"></td>
                        <td>{{ $slider->location == 1 ? "الصفحة الرئيسية" :($slider->location == 2 ? "صفحة البحث": "صفحة تفاصيل الاعلانلأ") }}</td>
                        <td>
                            <a title="تعديل" href="/webadmin/sliders/{{$slider->id}}/edit"><i
                                    class="fa fa-edit"></i></a>
                            <form class="inline-form-style"
                                  action="/webadmin/sliders/{{ $slider->id }}"
                                  method="post">
                                <button type="submit" class="trash-btn">
                                    <span class="fa fa-trash"></span>
                                </button>
                                <input type="hidden" name="_method" value="delete"/>
                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>

        </div>
    </div>
@endsection

@section('footer')
    {{--{!! Html::script('admin/vendors/custom/datatables/datatables.bundle.js') !!}--}}
    {{--{!! Html::script('admin/custom/js/countrcountriess!!}--}}
@endsection